//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClientService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVelibInformationService", CallbackContract=typeof(MyClientService.ServiceReference1.IVelibInformationServiceCallback))]
    public interface IVelibInformationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibInformationService/Calculate", ReplyAction="http://tempuri.org/IVelibInformationService/CalculateResponse")]
        void Calculate(int nOp, double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibInformationService/Calculate", ReplyAction="http://tempuri.org/IVelibInformationService/CalculateResponse")]
        System.Threading.Tasks.Task CalculateAsync(int nOp, double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibInformationService/SubscribeCalculatedEvent", ReplyAction="http://tempuri.org/IVelibInformationService/SubscribeCalculatedEventResponse")]
        void SubscribeCalculatedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibInformationService/SubscribeCalculatedEvent", ReplyAction="http://tempuri.org/IVelibInformationService/SubscribeCalculatedEventResponse")]
        System.Threading.Tasks.Task SubscribeCalculatedEventAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibInformationService/SubscribeCalculationFinishedEvent", ReplyAction="http://tempuri.org/IVelibInformationService/SubscribeCalculationFinishedEventResp" +
            "onse")]
        void SubscribeCalculationFinishedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibInformationService/SubscribeCalculationFinishedEvent", ReplyAction="http://tempuri.org/IVelibInformationService/SubscribeCalculationFinishedEventResp" +
            "onse")]
        System.Threading.Tasks.Task SubscribeCalculationFinishedEventAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibInformationServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibInformationService/Calculated")]
        void Calculated(int nOp, double dblNum1, double dblNum2, double dblResult);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibInformationService/CalculationFinished")]
        void CalculationFinished();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibInformationServiceChannel : MyClientService.ServiceReference1.IVelibInformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibInformationServiceClient : System.ServiceModel.DuplexClientBase<MyClientService.ServiceReference1.IVelibInformationService>, MyClientService.ServiceReference1.IVelibInformationService {
        
        public VelibInformationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VelibInformationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VelibInformationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibInformationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibInformationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Calculate(int nOp, double dblNum1, double dblNum2) {
            base.Channel.Calculate(nOp, dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task CalculateAsync(int nOp, double dblNum1, double dblNum2) {
            return base.Channel.CalculateAsync(nOp, dblNum1, dblNum2);
        }
        
        public void SubscribeCalculatedEvent() {
            base.Channel.SubscribeCalculatedEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeCalculatedEventAsync() {
            return base.Channel.SubscribeCalculatedEventAsync();
        }
        
        public void SubscribeCalculationFinishedEvent() {
            base.Channel.SubscribeCalculationFinishedEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeCalculationFinishedEventAsync() {
            return base.Channel.SubscribeCalculationFinishedEventAsync();
        }
    }
}
